name: Entrega Continua

on:
  workflow_call:

jobs:
  EC2:
    runs-on: ubuntu-latest
    steps:
      - name: Download a Build Artifact # baixando o binário compilado da aplicação em Go
        uses: actions/download-artifact@v3.0.0
        with:
          # Artifact name
          name: programa

      - uses: actions/checkout@v3 # para ter os arquivos estáticos da aplicação (html, css...)

      - name: Deploy to Staging server
        uses: easingthemes/ssh-deploy@main
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          ARGS: "-rlgoDzvc -i"
          # SOURCE: "dist/"
          REMOTE_HOST: ${{ secrets.REMOTE_HOST }} # no painel da EC2, seleciona sua instancia e nos detalhes dela já tem o IPV4 público
          REMOTE_USER: ${{ secrets.REMOTE_USER }} # com sua instancia selecionada, clica em conectar, lá tem o usuário
          # TARGET: ${{ secrets.REMOTE_TARGET }}
          TARGET: /home/${{ secrets.REMOTE_USER }}
          EXCLUDE: "/dist/, /node_modules/, /postgres-data/"

      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: ${{ secrets.REMOTE_HOST }}
          username: ${{ secrets.REMOTE_USER }}
          # password: ${{ secrets.PASSWORD }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          # port: ${{ secrets.PORT }}
          port: 22
          script: |
            export HOST=${{ secrets.DBHOST }}
            export USER=${{ secrets.DBUSER }}
            export PASSWORD=${{ secrets.DBPASSWORD }}
            export DBNAME=${{ secrets.DBNAME }}
            export DBPORT=${{ secrets.DBPORT }}
            export PORT=8000
            chmod +x
            nohup ./main &
          # pra eu lembrar apenas, estou usando o usuário padrao do postgres que é postgres kek,
          # outra coisa, a senha é a senha quando vc cria o banco no RDS, DBName msm da fase de testes => root
          # mais uma, esse PORT é a porta onde a aplicacao vai rodar
